# font_family CodeNewRoman Nerd Font Mono
font_size 14
font_family      family="Iosevka Fixed"
bold_font        auto
italic_font      auto
bold_italic_font auto

# Tokyo Night
include lackluster.conf

background_opacity 1.00
