# font_family CodeNewRoman Nerd Font Mono
font_size 14
font_family      family='Iosevka Fixed' postscript_name=Iosevka-Fixed
bold_font        family='Iosevka Fixed' style=Bold
italic_font      family='Iosevka Fixed' style='Italic'
bold_italic_font family='Iosevka Fixed' style='Bold Italic'

# Tokyo Night
include lackluster.conf

background_opacity 1.00
