[General]
frontendId=org.albert.frontend.widgetboxmodel
hotkey=Ctrl+Space
showTray=true
terminal=terminator -x

[org.albert.extension.applications]
enabled=true

[org.albert.extension.calculator]
enabled=true

[org.albert.extension.chromium]
enabled=false

[org.albert.extension.files]
enabled=true
fuzzy=true

[org.albert.extension.terminal]
enabled=true

[org.albert.frontend.qmlboxmodel]
alwaysOnTop=true
clearOnHide=false
hideOnClose=false
hideOnFocusLoss=true
showCentered=true
stylePath=/usr/share/albert/org.albert.frontend.qmlboxmodel/styles/BoxModel/MainComponent.qml
windowPosition=@Point(609 303)

[org.albert.frontend.widgetboxmodel]
alwaysOnTop=true
clearOnHide=false
displayIcons=true
displayScrollbar=true
displayShadow=true
hideOnClose=false
hideOnFocusLoss=true
itemCount=7
showCentered=false
theme=Yosemite Dark
windowPosition=@Point(591 62)
